#!/usr/bin/env python3
"""Reproduce a local-only, manually reviewed small-sample content audit.

The annotations below were assigned by the assistant after reading the saved
articles, not generated by an NLP classifier and not independently human-rated.
No network, trading, training, or main-report mutation occurs in this script.
"""
from __future__ import annotations

import hashlib
import json
import math
from collections import Counter
from datetime import datetime, timedelta
from pathlib import Path
from zoneinfo import ZoneInfo

ROOT = Path(__file__).resolve().parents[1]
BASE = ROOT / "reports/market_impact_data_audit_20261007"
SOURCE = BASE / "alpaca"
STOCKS = ["NVDA", "TSLA", "PLTR", "SNDK"]
CATEGORIES = {
    "company_event": "公司具体事件报道（是否首次新信息另行标注）",
    "market_review": "行情或技术回顾",
    "opinion": "观点解读",
    "multi_company": "多公司综述",
    "not_direct": "非直接相关",
}

# category, target role, extractability, Chinese rationale, novelty, related IDs.
# All factual descriptions are claims present in the saved source, not verified
# company facts. No English source quotations are reproduced in the output.
REVIEW = {
    ("NVDA", "62069776"): (
        "opinion", "background", "limited",
        "主体是苹果联合创始人与分析师对聊天机器人的观点。英伟达安全平台只在末段出现，不能将全文情绪直接视为英伟达情绪；可单独抽取文中平台及合作方主张。",
        "背景事件首次出现时间未验证；同库另一报道将平台发布时间写为此前周一。", ["62131571"]),
    ("NVDA", "62107232"): (
        "opinion", "secondary", "limited",
        "主体是投资者对人工智能估值与投资支出的看法及期权布局。英伟达只是多个持仓标的之一；可抽取报道声称的持仓变化，但它不是公司经营公告。",
        "持仓变化的首次公开时间未验证；不能把评论发表时间当作公司事件时间。", []),
    ("NVDA", "62142510"): (
        "company_event", "primary", "yes",
        "正文报道新增1500亿美元回购授权、剩余额度及盘中涨幅，可提取公司、动作和金额。金额是新闻中的主张，尚未核对原始公告。",
        "并非可确认的新事件：同日更早的62131571已经报道相同回购，并写明董事会授权日期为9月28日。", ["62131571"]),
    ("NVDA", "62171753"): (
        "multi_company", "one_of_many", "yes",
        "六家公司期权异动列表，英伟达有单独表格行及解释。可抽取期权方向、期限与成交量，但报道的看多标签属于供应商推断，不能当作真实交易意图或公司新闻。",
        "属于交易观察数据；不是新的公司经营事件。", []),
    ("NVDA", "62208307"): (
        "opinion", "primary", "limited",
        "讨论预测市场参与者对英伟达价格区间的预期，并回顾已发生行情。可抽取带来源的概率主张；正文首段有缺失目标价的句子，概率表述需逐项核验。",
        "属于市场观点快照，缺少独立的原始盘口观察时间与合约规则。", []),
    ("TSLA", "62075519"): (
        "company_event", "co_primary", "limited",
        "只有标题，内容是另一家公司向特斯拉提出首批500辆自动驾驶出租车的采购询问。可以提取询问主体、对象和规模，不能升级为已签订单或已交付。",
        "仅标题事件主张，未核验询问原文及特斯拉确认。", []),
    ("TSLA", "62119909"): (
        "opinion", "background", "limited",
        "主要讨论债券收益率、美光财报、博通交易及市场策略。特斯拉只在大型科技股资金流列表中出现；可提取作者声称的资金流方向，无法据此生成特斯拉新事件。",
        "未发现特斯拉特有的新经营事件；全文还含投稿者营销内容。", []),
    ("TSLA", "62145395"): (
        "opinion", "primary", "yes",
        "主体是前高管对汽车现金流支持机器人业务的解读，并重述交付量、储能部署及预期差。可抽取这些明确数字，但前高管看法与公司正式指引应分字段。",
        "评论与交付数据重述；正文已称报告后股价上涨，不能当作最早的交付发布。", []),
    ("TSLA", "62174431"): (
        "multi_company", "co_primary", "yes",
        "比较数家科技公司上涨期间某经纪平台用户的买卖比例，特斯拉是主要例子之一。可抽取平台特定的日/月比例，但不能代表全体散户，更不能替代富途原始帖子。",
        "回顾此前周五交易，并加入作者解释；不是特斯拉经营公告。", []),
    ("TSLA", "62203364"): (
        "multi_company", "background", "limited",
        "主体是标普指数创新高与多数成分股表现的差异。特斯拉仅在距离历史高点的比较中出现；该tag只能说明背景提及。",
        "广泛行情统计与评论，无特斯拉特有新事件。", []),
    ("PLTR", "62081426"): (
        "company_event", "primary", "limited",
        "只有标题，称交易员传阅匿名卖方机构关于2.5亿美元税务局合同的说法。可提取主体、金额和传闻属性；不能改写成公司已获合同。链接还是股票报价页，非稳定文章详情。",
        "未核实传闻；需保留匿名来源和不确定性。", []),
    ("PLTR", "62107232"): (
        "opinion", "secondary", "limited",
        "与英伟达层抽到的是同一篇文章。主体仍是投资者及人工智能估值争论，Palantir只占持仓列表一项；可抽取持仓变化主张，不能按全文给公司事件定性。",
        "跨股票重复抽样同一文章；不是另一个独立事件。", []),
    ("PLTR", "62135784"): (
        "company_event", "primary", "yes",
        "主体为Palantir与Armada的主权人工智能基础设施合作，含离线环境与制造范围等具体主张；后半部混入技术走势、盈利预期及基金卖股信息，适合分段提取。",
        "合作在前日晚62124826已出现；本篇属于后续报道，不能作为合作首次发布时间。", ["62124826", "62142882"]),
    ("PLTR", "62142882"): (
        "not_direct", "secondary", "limited",
        "主体是基金买入Rocket Lab及其业务前景，Palantir仅为同一基金减仓对照。可以抽取卖出金额，但全文正面语气主要针对另一家公司。",
        "减持约395万美元也在62135784出现，属于可重复的次要事实。", ["62135784"]),
    ("PLTR", "62185722"): (
        "company_event", "primary", "limited",
        "只有标题，称英国金融监管机构不再续签短期技术与金融犯罪合同。可提取合同未续签主张，金额、到期时间、实质影响均缺失。",
        "仅标题事实主张，尚未核对监管机构原文。", []),
    ("SNDK", "62071303"): (
        "not_direct", "background", "limited",
        "主体是美光拆股猜测与社交讨论。闪迪仅作为高股价但未拆股的对比例子；不能将美光用户观点贴到闪迪上。",
        "未发现闪迪新事件；比较性价格事实不等于拆股计划。", []),
    ("SNDK", "62100903"): (
        "market_review", "primary", "yes",
        "回顾闪迪盘前上涨、存储需求、同行财报、既有评级及未来财报日期。可提取价格、日期和同行事件，但文中没有证明新发布的闪迪经营公告。",
        "与下一日62134375重复美光财报、分析师预期与基金权重背景；当日价格观察不同。", ["62134375"]),
    ("SNDK", "62117004"): (
        "multi_company", "one_of_many", "yes",
        "十家公司期权异动列表，闪迪有明确表格行。可抽取期权报价与期限，不能将供应商的看空分类直接当作散户情绪或已验证预测。",
        "交易观察，不是公司经营事件；模板化措辞不代表与另一日期的列表是同一事件。", []),
    ("SNDK", "62134375"): (
        "market_review", "primary", "yes",
        "主体是闪迪当日回撤及年内上涨背景，重述存储供需、美光业绩、财报预期与基金权重。可以抽取描述性事实，不能把标题的大涨回顾当作未来看涨预测。",
        "与62100903存在重复背景，但更新了价格；需要区分共同事件与每日行情片段。", ["62100903"]),
    ("SNDK", "62194029"): (
        "not_direct", "background", "no",
        "只有标题，报道希捷与东芝争购TDK硬盘磁头业务，主体均非闪迪。标题明确是此前报道；闪迪tag不足以抽取其公司事实。",
        "转述此前消息，首次报道时间未知；不能推断闪迪参与该交易。", []),
}


def dt(value):
    return datetime.fromisoformat(value.replace("Z", "+00:00"))


def ceil5(value):
    return datetime.fromtimestamp(math.ceil(value.timestamp() / 300) * 300, value.tzinfo)


def load(path):
    return json.loads(path.read_text())


def hash_file(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main():
    news = load(SOURCE / "news_normalized.json")
    labels = load(SOURCE / "exploratory_labels.json")
    summary = load(SOURCE / "summary.json")
    by_id = {row["id"]: row for row in news}
    sample, strata = [], []
    for symbol in STOCKS:
        rows = sorted((row for row in news if symbol in row["symbols"]),
                      key=lambda row: (row["created_at"], row["id"]))
        # Python round uses ties-to-even. The exact selected ranks are recorded.
        ranks = [round(i * (len(rows) - 1) / 4) for i in range(5)]
        strata.append({"symbol": symbol, "population_tagged_articles": len(rows),
                       "zero_based_ranks": ranks, "event_ids": [rows[i]["id"] for i in ranks]})
        for rank in ranks:
            article = rows[rank]
            cat, role, facts, rationale, novelty, related = REVIEW[(symbol, article["id"])]
            sample.append({
                "event_id": article["id"], "symbol": symbol, "stratum_rank_zero_based": rank,
                "url": article["url"], "created_at": article["created_at"],
                "updated_at": article["updated_at"], "text_words": article["text_words"],
                "headline_only": not bool(article["text"].strip()),
                "category": cat, "category_zh": CATEGORIES[cat], "target_role": role,
                "target_is_main_subject": role in {"primary", "co_primary"},
                "company_fact_extractability": facts,
                "interpretation_zh": rationale, "novelty_and_duplication_zh": novelty,
                "potential_related_event_ids": related,
                "source_claims_independently_verified": False,
                "english_quote_word_count": 0,
            })

    assert len(sample) == 20 and len(REVIEW) == 20
    by_category = Counter(row["category_zh"] for row in sample)
    unique_ids = set(row["event_id"] for row in sample)
    duplicate_ids = {key: value for key, value in Counter(row["event_id"] for row in sample).items() if value > 1}
    prices = {}
    for path in sorted(SOURCE.glob("bars_*_*.json")):
        for symbol, rows in (load(path).get("bars") or {}).items():
            prices.setdefault(symbol, {}).update({dt(row["t"]): row for row in rows})

    available = [row for row in labels if row["status"] == "exploratory_label_available"]
    failures = []
    revised_available = []
    for row in available:
        article = by_id[row["event_id"]]
        created, updated = dt(article["created_at"]), dt(article["updated_at"])
        entry, end = dt(row["entry_at"]), dt(row["exit_at"])
        expected_entry = ceil5(max(created, updated) + timedelta(seconds=60))
        stock = prices[row["symbol"]][end]["o"] / prices[row["symbol"]][entry]["o"] - 1
        spy = prices["SPY"][end]["o"] / prices["SPY"][entry]["o"] - 1
        checks = {
            "entry_time": entry == expected_entry,
            "horizon_60m": end - entry == timedelta(minutes=60),
            "stock_return": math.isclose(stock, row["stock_return"], rel_tol=1e-12, abs_tol=1e-12),
            "spy_return": math.isclose(spy, row["spy_return"], rel_tol=1e-12, abs_tol=1e-12),
            "excess_return": math.isclose(stock-spy, row["excess_return"], rel_tol=1e-12, abs_tol=1e-12),
            "updated_before_entry": updated <= entry,
            "availability_unverified": row["historical_availability_verified"] is False,
        }
        if not all(checks.values()):
            failures.append({"event_id": row["event_id"], "symbol": row["symbol"], "checks": checks})
        if updated > created:
            revised_available.append({"event_id": row["event_id"], "symbol": row["symbol"]})

    revised = [row for row in news if dt(row["updated_at"]) > dt(row["created_at"])]
    crosses_horizon = []
    for row in revised:
        created, updated = dt(row["created_at"]), dt(row["updated_at"])
        counterfactual_exit = ceil5(created + timedelta(seconds=60)) + timedelta(minutes=60)
        if updated > counterfactual_exit:
            local = created.astimezone(ZoneInfo("America/New_York"))
            crosses_horizon.append({
                "event_id": row["id"], "url": row["url"], "created_at": row["created_at"],
                "updated_at": row["updated_at"],
                "revision_delay_hours": round((updated-created).total_seconds()/3600, 4),
                "counterfactual_created_based_exit": counterfactual_exit.isoformat(),
                "original_created_local_time": local.isoformat(),
                "note_zh": "原发布时间在盘前；此处仅演示版本跨越原始时间加60分钟的风险，不代表原始时点存在合格盘中样本。",
                "current_label_records": [r for r in labels if r["event_id"] == row["id"]],
            })

    output = {
        "schema_version": 1,
        "audit_scope_zh": "只审阅已下载的本地文章与探索标签；不联网、不训练、不运行交易，也不修改主报告。",
        "reviewer_zh": "本助手逐篇阅读正文后标注；没有调用外部分类模型，也没有独立人类复核。这不是已建立的NLP系统或人工金标准。",
        "sampling": {
            "population_articles": len(news), "population_stock_article_pairs": len(labels),
            "sample_stock_article_pairs": len(sample), "sample_unique_articles": len(unique_ids),
            "rule_zh": "每只股票按(created_at,id)升序排序；取Python round(i*(n-1)/4), i=0..4的0基序号。允许跨股票抽到同一文章。",
            "sort_id_type": "string", "strata": strata,
            "duplicate_article_ids_across_strata": duplicate_ids,
            "interpretation_limit_zh": "确定性的分层等距小样本，不是随机代表样本；下列计数只描述这20个股票-文章对，不能外推总体比例或NLP准确率。",
        },
        "category_definitions_zh": {
            "company_event": "报道目标公司的具体动作或事件主张；是否已证实、是否首次出现分别标注。",
            "market_review": "主要回顾目标公司的价格、技术走势及既有经营背景。",
            "opinion": "以观点、分析或市场预期解读为主体；可含可抽取的事实主张。",
            "multi_company": "比较或列举多家公司，目标公司是其一。",
            "not_direct": "文章主体是另一家公司/事件，目标仅为背景或次要对照。",
        },
        "sample_counts": {
            "category_counts_stock_article_pairs": dict(by_category),
            "headline_only_stock_article_pairs": sum(row["headline_only"] for row in sample),
            "headline_only_unique_articles": sum(not bool(by_id[i]["text"].strip()) for i in unique_ids),
            "target_is_main_subject_pairs": sum(row["target_is_main_subject"] for row in sample),
            "target_not_main_subject_pairs": sum(not row["target_is_main_subject"] for row in sample),
            "fact_extractability_pairs": dict(Counter(row["company_fact_extractability"] for row in sample)),
            "company_event_pairs_with_body": sum(row["category"] == "company_event" and not row["headline_only"] for row in sample),
            "company_event_pairs_headline_only": sum(row["category"] == "company_event" and row["headline_only"] for row in sample),
            "all_source_claims_unverified": True,
        },
        "samples": sample,
        "potential_event_clusters": [
            {"event_ids": ["62131571", "62142510"], "type": "same_company_event",
             "reason_zh": "均报道英伟达新增1500亿美元回购；较早正文还标注9月28日授权。新闻ID不同不代表新事件。"},
            {"event_ids": ["62124826", "62135784"], "type": "same_company_event",
             "reason_zh": "前一日晚标题快讯已提到Palantir与Armada合作，后一日为较长报道。"},
            {"event_ids": ["62135784", "62142882"], "type": "shared_secondary_fact",
             "reason_zh": "重复基金减持Palantir约395万美元的次要事实；整篇文章主体不同，不应简单删除其中一篇。"},
            {"event_ids": ["62100903", "62134375"], "type": "shared_background_with_new_market_snapshot",
             "reason_zh": "重用同行财报、盈利预期、评级与基金权重背景，但当天行情不同。"},
        ],
        "label_audit": {
            "all_records": len(labels), "status_counts": dict(Counter(row["status"] for row in labels)),
            "available_return_label_pairs": len(available),
            "available_return_label_unique_articles": len(set(row["event_id"] for row in available)),
            "available_return_label_pairs_with_body": sum(bool(by_id[row["event_id"]]["text"].strip()) for row in available),
            "available_return_label_unique_articles_with_body": len({row["event_id"] for row in available if by_id[row["event_id"]]["text"].strip()}),
            "all_90_labels_recomputed_from_saved_bars": len(available) == 90 and not failures,
            "recomputation_failures": failures,
            "fields_present": sorted({key for row in available for key in row}),
            "available_labels_with_unverified_historical_availability": sum(row["historical_availability_verified"] is False for row in available),
            "interpretation_zh": "90条均是根据后来价格计算的收益标签，没有预测分数、模型或交易记录；不能称为90次预测、90笔交易、准确率或策略收益。",
            "independence_limit_zh": "81篇不同ID文章也不等于81个独立事件；仍存在重复事件、共同背景、同一文章多股票以及收益窗口重叠。",
            "formula_zh": "假设可用时间=max(创建,更新)；增加60秒后上取整到5分钟起点，取该起点及60分钟后5分钟bar的开盘价，个股收益减SPY同窗口收益。",
            "execution_limit_zh": "历史bar开盘价不是可保证的成交价；没有点差、滑点、佣金或真实传输延迟。标签可计算不等于新闻当时可见。",
            "revision_audit": {
                "revised_articles_in_population": len(revised),
                "revised_articles_updated_after_full_download_window_end": sum(dt(row["updated_at"]) > dt(summary["end"]) for row in revised),
                "articles_revised_more_than_60m_after_created": sum(dt(row["updated_at"])-dt(row["created_at"]) > timedelta(minutes=60) for row in revised),
                "articles_updated_after_created_based_60m_exit": crosses_horizon,
                "revised_articles_in_available_labels": len({row["event_id"] for row in revised_available}),
                "revised_stock_article_pairs_in_available_labels": len(revised_available),
                "available_labels_updated_after_actual_entry": sum(dt(by_id[row["event_id"]]["updated_at"]) > dt(row["entry_at"]) for row in available),
                "conclusion_zh": "现计算按最后更新时间推迟窗口，没有发现90条中修订晚于其入场起点的情况。但缺少旧版本与真实到达时间，仍不能还原原始时点可见文本。跨原60分钟窗口的修订与跨整段下载窗口分别报告。",
            },
        },
        "next_steps_zh": [
            "在股票tag后增加主体/段落相关性识别，保存事件事实、观点和行情回顾的区别。",
            "将只含标题、匿名传闻、采购询问等设为独立证据等级，禁止升级成确认事件。",
            "同一公司事件跨文章聚类，保留跟进事实与旧背景，防止重复计权和训练测试泄漏。",
            "继续采集原始版本及首次接收时间；现有返回正文只能支撑探索性配对。",
            "扩大独立复核样本后再评估抽取或分类模型；本样本不支持准确率、交易优势或普遍覆盖结论。",
        ],
        "provenance": {
            "input_sha256": {str(p.relative_to(ROOT)): hash_file(p) for p in [
                SOURCE / "news_normalized.json", SOURCE / "exploratory_labels.json", SOURCE / "summary.json"]},
            "script": str(Path(__file__).relative_to(ROOT)),
            "english_quotes_reproduced": 0,
        },
    }
    destination = BASE / "news_quality.json"
    destination.write_text(json.dumps(output, ensure_ascii=False, indent=2) + "\n")
    print(json.dumps({"output": str(destination), "sampling": output["sampling"],
                      "sample_counts": output["sample_counts"], "label_audit": output["label_audit"]},
                     ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
